### ISSUE TITLE
Typo "RP_Inpure" instead of "RP_Impure"

### ISSUE THREAD

**Issue by RebeccaStevens** [moritz-h/satisfactory-mapdata#3]
I'd imagine this an issue with the game data itself rather than how this mod extracts the data, but just thought I'd open an issue in case.

**Comment by moritz-h** [comment]
Yes, this is a typo in the base game. You can look into the header files in the game install directory and see that it is the same there. I'm using the original enum type serialized to json through the Unreal serialization system. Therefore, it is just 1:1 the original value name.

I think in the game they fixed it, by naming the localized display text correctly and avoided a breaking change in the actually enum name. But it would not make sense for this mod to output a localized nice name as it would just make parsing of the output unnecessary complicated.
